### ISSUE TITLE
Should not be necessary anymore

### ISSUE THREAD

**Issue by step21** [vasi/hfsj#1]
#In case anybody is still here - I recently compiled an updated version of this driver (9.4) with kerenl 4.4.0, so I guess this should be newer than this repository by now.
The only problem with that is now that somewhere - not in an actual new kernel version but at least some maintenance update from ubuntu from 4.4.0-52 to 4.4.0-57 or 59 the declaration of a a posix function was changed, so with the latest kernels on 16.04 or 14.04.5 the driver doesn't compile anymore.

**Comment by vasi** [comment]
Thanks, it's good to know Paragon's driver compiles on 4.4.0 now. As you mentioned, it continues to break every so often—that's the point of this repo.
